# Autogenerated wrapper script for GumboBinaries_jll for armv7l-linux-gnueabihf
export libgumbo

JLLWrappers.@generate_wrapper_header("GumboBinaries")
JLLWrappers.@declare_library_product(libgumbo, "libgumbo.so.3")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgumbo,
        "lib/libgumbo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
