# Autogenerated wrapper script for GumboBinaries_jll for i686-w64-mingw32
export libgumbo

JLLWrappers.@generate_wrapper_header("GumboBinaries")
JLLWrappers.@declare_library_product(libgumbo, "libgumbo-3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgumbo,
        "bin\\libgumbo-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
